# Generated by Django 2.1.5 on 2019-01-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='etat',
            field=models.CharField(choices=[('affame', 'affame'), ('repus', 'repus'), ('endormi', 'endormi'), ('fatigue', 'fatigue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalerie.Equipement'),
        ),
    ]
