# Generated by Django 2.1.5 on 2019-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0002_auto_20190126_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='lieu',
            field=models.TextField(),
        ),
    ]
